"""
Apache Airflow DAG — Lineage Test Pipeline

Auto-generated by AI Data Engineer Agent
Description: Automated ETL Pipeline
Version: 1
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

# --- Embedded Data Transformation Code ---
# No inline python code provided.

# --- Default Airflow Arguments ---
default_args = {
    'owner': 'ai_data_engineer_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

# --- DAG Definition ---
with DAG(
    dag_id='lineage_test_pipeline',
    default_args=default_args,
    description='AI Generated DAG',
    schedule_interval='@daily',
    catchup=False,
    tags=['ai_generated', 'etl', 'data'],
) as dag:


def task_1_callable(**context):
    """Task 1 (extract)"""
    print("Airflow Task Executing: Task 1")
    # Injected runtime context
    ti = context.get('ti')
    if ti:
        ti.xcom_push(key='status_1', value='SUCCESS')
    return {"node_id": "1", "status": "COMPLETED"}

1_task = PythonOperator(
    task_id='1',
    python_callable=task_1_callable,
    dag=dag,
)
def task_2_callable(**context):
    """Task 2 (load)"""
    print("Airflow Task Executing: Task 2")
    # Injected runtime context
    ti = context.get('ti')
    if ti:
        ti.xcom_push(key='status_2', value='SUCCESS')
    return {"node_id": "2", "status": "COMPLETED"}

2_task = PythonOperator(
    task_id='2',
    python_callable=task_2_callable,
    dag=dag,
)

    # Task Dependency Chain
1_task >> 2_task