"""
Apache Airflow DAG — Lineage Test Pipeline

Auto-generated by AI Data Engineer Agent
Description: Automated ETL Pipeline
Version: 1
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

# --- Embedded Data Transformation Code ---
# No inline python code provided.

# --- Default Airflow Arguments ---
default_args = {
    'owner': 'ai_data_engineer_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

# --- DAG Definition ---
with DAG(
    dag_id="lineage_test_pipeline",
    default_args=default_args,
    description="AI Generated DAG",
    schedule_interval='@daily',
    catchup=False,
    tags=['ai_generated', 'etl', "data"],
) as dag:

    def task_task_1_1_callable(**context):
        """Task 1 (extract)"""
        print("Airflow Task Executing: Task 1")
        ti = context.get('ti')
        if ti:
            ti.xcom_push(key='status_task_1_1', value='SUCCESS')
        return {"node_id": "task_1_1", "status": "COMPLETED"}

    task_1_1_task = PythonOperator(
        task_id="task_1_1",
        python_callable=task_task_1_1_callable,
        dag=dag,
    )

    def task_task_2_2_callable(**context):
        """Task 2 (load)"""
        print("Airflow Task Executing: Task 2")
        ti = context.get('ti')
        if ti:
            ti.xcom_push(key='status_task_2_2', value='SUCCESS')
        return {"node_id": "task_2_2", "status": "COMPLETED"}

    task_2_2_task = PythonOperator(
        task_id="task_2_2",
        python_callable=task_task_2_2_callable,
        dag=dag,
    )

    task_1_1_task >> task_2_2_task