"""
Application — Apache Airflow DAG Exporter

Converts synthesized pipeline specifications and code into standalone,
executable Apache Airflow DAG Python scripts.
"""

from __future__ import annotations

import re
from typing import Any

from app.domain.entities import Pipeline


class AirflowDAGExporter:
    """
    Exports a Pipeline entity or specification dictionary into a production-ready
    Apache Airflow DAG (.py file).
    """

    def export_dag_code(self, pipeline: Pipeline) -> str:
        spec = pipeline.spec or {}
        nodes = spec.get("nodes", [])
        code_dict = spec.get("code", {})
        python_code = code_dict.get("python", "")
        
        dag_id = self._slugify(pipeline.name)
        schedule = spec.get("parameters", {}).get("schedule_interval", "@daily")
        max_retries = spec.get("parameters", {}).get("max_retries", 2)

        # Sanitize Python code indentation for embedding
        embedded_python = self._format_embedded_code(python_code)

        # Construct Airflow tasks
        task_definitions = []
        task_ids = []

        for index, node in enumerate(nodes, 1):
            n_id = self._slugify(node.get("id", f"step_{index}"))
            label = node.get("label", f"Task {index}")
            node_type = node.get("type", "transformer")
            
            task_ids.append(n_id)
            task_definitions.append(f"""
def task_{n_id}_callable(**context):
    \"\"\"{label} ({node_type})\"\"\"
    print("Airflow Task Executing: {label}")
    # Injected runtime context
    ti = context.get('ti')
    if ti:
        ti.xcom_push(key='status_{n_id}', value='SUCCESS')
    return {{"node_id": "{n_id}", "status": "COMPLETED"}}

{n_id}_task = PythonOperator(
    task_id='{n_id}',
    python_callable=task_{n_id}_callable,
    dag=dag,
)""")

        # Build task dependency chain (e.g. task1 >> task2 >> task3)
        if len(task_ids) > 1:
            dependency_chain = " >> ".join([f"{tid}_task font-mono" for tid in task_ids]).replace(" font-mono", "")
            dependency_code = f"# Task Dependency Chain\n{dependency_chain}"
        elif len(task_ids) == 1:
            dependency_code = f"# Single Task\n{task_ids[0]}_task"
        else:
            dependency_code = "# No tasks defined"

        airflow_script = f'''"""
Apache Airflow DAG — {pipeline.name}

Auto-generated by AI Data Engineer Agent
Description: {pipeline.description or "Automated ETL Pipeline"}
Version: {pipeline.version}
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

# --- Embedded Data Transformation Code ---
{embedded_python}

# --- Default Airflow Arguments ---
default_args = {{
    'owner': 'ai_data_engineer_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': {max_retries},
    'retry_delay': timedelta(minutes=5),
}}

# --- DAG Definition ---
with DAG(
    dag_id='{dag_id}',
    default_args=default_args,
    description='{pipeline.description or "AI Generated DAG"}',
    schedule_interval='{schedule}',
    catchup=False,
    tags=['ai_generated', 'etl', '{spec.get("source", "data").lower()}'],
) as dag:

{''.join(task_definitions)}

    {dependency_code}
'''
        return airflow_script.strip()

    def _slugify(self, text: str) -> str:
        slug = re.sub(r"[^\w\s-]", "", text).strip().lower()
        slug = re.sub(r"[-\s]+", "_", slug)
        return slug or "pipeline_dag"

    def _format_embedded_code(self, code: str) -> str:
        if not code:
            return "# No inline python code provided."
        return "\n".join([line for line in code.splitlines() if not line.startswith("if __name__ ==")])
