"""
Application — Apache Airflow DAG Exporter

Converts synthesized pipeline specifications and code into standalone,
executable Apache Airflow DAG Python scripts.
"""

from __future__ import annotations

import json
import re
from typing import Any

from app.domain.entities import Pipeline


class AirflowDAGExporter:
    """
    Exports a Pipeline entity or specification dictionary into a production-ready
    Apache Airflow DAG (.py file).
    """

    def export_dag_code(self, pipeline: Pipeline) -> str:
        spec = pipeline.spec or {}
        nodes = spec.get("nodes", [])
        code_dict = spec.get("code", {})
        python_code = code_dict.get("python", "")
        
        dag_id = self._slugify_identifier(pipeline.name, prefix="dag")
        schedule = spec.get("parameters", {}).get("schedule_interval", "@daily")
        max_retries = spec.get("parameters", {}).get("max_retries", 2)

        # Sanitize Python code indentation for embedding
        embedded_python = self._format_embedded_code(python_code)
        
        # Safely escape description and tag strings for Python literal inclusion
        desc_escaped = json.dumps(pipeline.description or "AI Generated DAG")
        tag_source = self._slugify_identifier(spec.get("source", "data"), prefix="src")

        # Construct Airflow tasks
        task_definitions = []
        task_var_names = []

        for index, node in enumerate(nodes, 1):
            n_raw = node.get("id") or f"step_{index}"
            n_id = self._slugify_identifier(n_raw, prefix=f"task_{index}")
            label = node.get("label", f"Task {index}")
            node_type = node.get("type", "transformer")
            
            var_name = f"{n_id}_task"
            task_var_names.append(var_name)
            
            task_definitions.append(f"""    def task_{n_id}_callable(**context):
        \"\"\"{label} ({node_type})\"\"\"
        print("Airflow Task Executing: {label}")
        ti = context.get('ti')
        if ti:
            ti.xcom_push(key='status_{n_id}', value='SUCCESS')
        return {{"node_id": "{n_id}", "status": "COMPLETED"}}

    {var_name} = PythonOperator(
        task_id={json.dumps(n_id)},
        python_callable=task_{n_id}_callable,
        dag=dag,
    )""")

        # Build task dependency chain (e.g. task1 >> task2 >> task3)
        if len(task_var_names) > 1:
            dependency_code = "    " + " >> ".join(task_var_names)
        elif len(task_var_names) == 1:
            dependency_code = f"    # Single Task Execution\n    {task_var_names[0]}"
        else:
            dependency_code = "    # No tasks defined\n    pass"

        tasks_block = "\n\n".join(task_definitions) if task_definitions else ""

        airflow_script = f'''"""
Apache Airflow DAG — {pipeline.name}

Auto-generated by AI Data Engineer Agent
Description: {pipeline.description or "Automated ETL Pipeline"}
Version: {pipeline.version}
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

# --- Embedded Data Transformation Code ---
{embedded_python}

# --- Default Airflow Arguments ---
default_args = {{
    'owner': 'ai_data_engineer_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': {max_retries},
    'retry_delay': timedelta(minutes=5),
}}

# --- DAG Definition ---
with DAG(
    dag_id={json.dumps(dag_id)},
    default_args=default_args,
    description={desc_escaped},
    schedule_interval='{schedule}',
    catchup=False,
    tags=['ai_generated', 'etl', {json.dumps(tag_source)}],
) as dag:

{tasks_block}

{dependency_code}
'''
        return airflow_script.strip()

    def _slugify_identifier(self, text: str, prefix: str = "item") -> str:
        slug = re.sub(r"[^\w\s-]", "", text).strip().lower()
        slug = re.sub(r"[-\s]+", "_", slug)
        if not slug:
            return prefix
        if slug[0].isdigit():
            slug = f"{prefix}_{slug}"
        return slug

    def _format_embedded_code(self, code: str) -> str:
        if not code:
            return "# No inline python code provided."
        return "\n".join([line for line in code.splitlines() if not line.startswith("if __name__ ==")])

