"""
Application — dbt (Data Build Tool) Model Exporter

Converts synthesized pipeline specifications into modular dbt SQL transformation models
and schema definitions (schema.yml).
"""

from __future__ import annotations

import re
from typing import Any

from app.domain.entities import Pipeline


class DBTExporter:
    """
    Exports a Pipeline entity or specification dictionary into a dbt project structure
    containing SQL models and schema.yml configuration.
    """

    def export_dbt_project(self, pipeline: Pipeline) -> dict[str, str]:
        spec = pipeline.spec or {}
        nodes = spec.get("nodes", [])
        pipeline_slug = self._slugify(pipeline.name)

        model_sql = self._generate_sql_model(pipeline, nodes, spec)
        schema_yml = self._generate_schema_yml(pipeline_slug, nodes, spec)

        return {
            f"models/{pipeline_slug}.sql": model_sql,
            "models/schema.yml": schema_yml,
        }

    def _generate_sql_model(self, pipeline: Pipeline, nodes: list[dict[str, Any]], spec: dict[str, Any]) -> str:
        source_table = spec.get("source", "raw_source_table")
        
        sql_lines = [
            f"-- dbt Model: {self._slugify(pipeline.name)}",
            f"-- Description: {pipeline.description or 'Auto-generated by AI Data Engineer Agent'}",
            "{{ config(materialized='table') }}",
            "",
            "WITH source_data AS (",
            f"    SELECT * FROM {{{{ source('raw', '{source_table}') }}}}",
            "),",
        ]

        cte_names = []
        for idx, node in enumerate(nodes, 1):
            label = node.get("label", f"step_{idx}")
            node_id = self._slugify(label)
            prev_cte = cte_names[-1] if cte_names else "source_data"
            cte_names.append(node_id)

            if "clean" in label.lower() or "null" in label.lower():
                sql_lines.extend([
                    f"{node_id} AS (",
                    f"    SELECT *",
                    f"    FROM {prev_cte}",
                    "    WHERE updated_at IS NOT NULL",
                    "),",
                ])
            elif "aggregate" in label.lower() or "daily" in label.lower():
                sql_lines.extend([
                    f"{node_id} AS (",
                    "    SELECT",
                    "        DATE_TRUNC('day', created_at) AS event_date,",
                    "        COUNT(*) AS total_events,",
                    "        COUNT(DISTINCT user_id) AS unique_users",
                    f"    FROM {prev_cte}",
                    "    GROUP BY 1",
                    "),",
                ])
            else:
                sql_lines.extend([
                    f"{node_id} AS (",
                    "    SELECT *",
                    f"    FROM {prev_cte}",
                    "),",
                ])

        final_cte = cte_names[-1] if cte_names else "source_data"
        sql_lines.extend([
            "final AS (",
            f"    SELECT * FROM {final_cte}",
            ")",
            "",
            "SELECT * FROM final",
        ])

        return "\n".join(sql_lines)

    def _generate_schema_yml(self, model_name: str, nodes: list[dict[str, Any]], spec: dict[str, Any]) -> str:
        return f"""version: 2

models:
  - name: {model_name}
    description: "Auto-generated model for {model_name}."
    columns:
      - name: event_date
        description: "Primary timestamp of aggregated events."
        tests:
          - not_null
      - name: total_events
        description: "Count of processed records."
      - name: unique_users
        description: "Distinct user count metric."
"""

    def _slugify(self, text: str) -> str:
        slug = re.sub(r"[^\w\s-]", "", text).strip().lower()
        slug = re.sub(r"[-\s]+", "_", slug)
        return slug or "dbt_model"
