"""
Application — Prefect Flow Exporter

Converts synthesized pipeline specifications into Prefect 2.0/3.0 @flow and @task scripts.
"""

from __future__ import annotations

import re
from app.domain.entities import Pipeline


class PrefectExporter:
    """
    Exports a Pipeline entity or specification dictionary into a Prefect Flow script.
    """

    def export_flow_code(self, pipeline: Pipeline) -> str:
        spec = pipeline.spec or {}
        nodes = spec.get("nodes", [])
        code_dict = spec.get("code", {})
        python_code = code_dict.get("python", "")

        flow_name = self._slugify(pipeline.name)

        task_code_blocks = []
        task_calls = []

        for index, node in enumerate(nodes, 1):
            n_id = self._slugify(node.get("id", f"step_{index}"))
            label = node.get("label", f"Task {index}")
            
            task_code_blocks.append(f"""
@task(name="{label}")
def task_{n_id}():
    print("Executing Prefect Task: {label}")
    return {{"status": "SUCCESS", "node": "{n_id}"}}
""")
            task_calls.append(f"    res_{n_id} = task_{n_id}()")

        prefect_script = f'''"""
Prefect Flow — {pipeline.name}

Auto-generated by AI Data Engineer Agent
Version: {pipeline.version}
"""

from prefect import flow, task

{python_code}

{''.join(task_code_blocks)}

@flow(name="{pipeline.name}", description="{pipeline.description or 'AI Generated Pipeline'}")
def {flow_name}_flow():
    print("Starting Prefect Flow Execution...")
{chr(10).join(task_calls)}
    print("Prefect Flow Execution Completed Successfully!")

if __name__ == "__main__":
    {flow_name}_flow()
'''
        return prefect_script.strip()

    def _slugify(self, text: str) -> str:
        slug = re.sub(r"[^\w\s-]", "", text).strip().lower()
        slug = re.sub(r"[-\s]+", "_", slug)
        return slug or "prefect_flow"
